spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auction
    username: postgres
    password: 2177
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
logging:
  level:
    root: INFO
    ru.andreev.auction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE